name: Sync Upstream and Update Mirrors

on:
  schedule:
    # The nightly channel is usually updated at 01:00:00 UTC.
    - cron: "0 2 * * *" # *-*-* 02:00:00 UTC

    # The stable channel is usually updated before 17:00:00 UTC on Thursday.
    # It seems there are some stable users eagerly want to use the latest stable and
    # cannot afford a lengthy 24hrs delay. So poll once every hour here. ¯\_(ツ)_/¯
    # See: https://github.com/oxalica/rust-overlay/pull/166
    - cron: "0 14-20 * * THU" # Thu *-*-* 14..19:00:00 UTC
  workflow_dispatch:

jobs:
  sync-and-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          rm -rf ./*
          git clone https://github.com/oxalica/rust-overlay.git
          cp -rf ./rust-overlay/* ./
          rm -rf ./rust-overlay/
          rm -f .github/workflows/{ci.yaml,sync-channels.yaml,update-stable.yaml}

      - name: Replace Rust URLs
        run: |
          sed -i 's|https://static.rust-lang.org|https://mirrors.ustc.edu.cn/rust-static|g' lib/dist-root.nix
          sed -i 's|https://static.rust-lang.org|https://mirrors.ustc.edu.cn/rust-static|g' tests/default.nix
          rm -f .github/workflows/{ci.yaml,sync-channels.yaml,update-stable.yaml}

      - name: Commit changes
        id: commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add *
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: Update Rust URLs to USTC mirror"
            echo "has_commit=true" >> $GITHUB_OUTPUT
          else
            echo "has_commit=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.commit.outputs.has_commit == 'true'
        run: git push origin HEAD:master
