name: update-stable
on:
  push:
    branches:
      - master
    paths:
      - '*.nix'
      - '*.sh'
      - 'manifests/*.nix'
      - 'manifests/stable/*.nix'

  workflow_dispatch:

jobs:
  update-stable:
    name: Update "stable" branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Forward stable -> master
        run: |
          git checkout stable
          git merge --ff-only master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: stable
