name: update-stable
on:
  push:
    branches:
      - master
    paths:
      - '*.nix'
      - '*.sh'
      - 'manifests/*.nix'
      - 'manifests/stable/*.nix'

  workflow_dispatch:

jobs:
  update-stable:
    name: Update "stable" branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Update stable -> master
        run: |
          git checkout stable
          git merge --ff-only master
          git push stable:stable
